# Generated by Django 5.2.13 on 2026-04-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Center name')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Contact person')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('student_limit', models.PositiveIntegerField(default=10, verbose_name='Student limit')),
                ('price_per_student', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per student (UZS)')),
                ('contract_start', models.DateField(verbose_name='Contract start')),
                ('contract_end', models.DateField(verbose_name='Contract end')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Learning Center',
                'verbose_name_plural': 'Learning Centers',
                'db_table': 'learning_centers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('individual', 'Individual'), ('center', 'Learning Center')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount (UZS)')),
                ('currency', models.CharField(default='UZS', max_length=5)),
                ('payment_method', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('xazna', 'Xazna')], max_length=20)),
                ('started_at', models.DateTimeField(verbose_name='Started at')),
                ('ends_at', models.DateTimeField(verbose_name='Ends at')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
