# Generated by Django 5.2.13 on 2026-04-30 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[^@]+@[^@]+\\.[^@]+$', message='Enter a valid email address.')], verbose_name='Email address'),
        ),
    ]
