# Generated by Django 5.2.13 on 2026-05-01 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('audio_url', models.URLField(max_length=500, verbose_name='Audio URL')),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='Transcript')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'listening_tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListeningAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_score', models.PositiveIntegerField(default=0)),
                ('band_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_attempts', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listening.listeningtest')),
            ],
            options={
                'db_table': 'listening_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ListeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField(choices=[(1, 'Section 1'), (2, 'Section 2'), (3, 'Section 3'), (4, 'Section 4')])),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('matching_headings', 'Matching Headings'), ('matching_information', 'Matching Information'), ('tfng', 'True / False / Not Given'), ('ynng', 'Yes / No / Not Given'), ('summary_completion', 'Summary Completion'), ('sentence_completion', 'Sentence Completion'), ('short_answer', 'Short Answer'), ('form_completion', 'Form Completion'), ('table_completion', 'Table Completion'), ('diagram_labelling', 'Diagram Labelling')], max_length=30)),
                ('question_text', models.TextField()),
                ('correct_answer', models.CharField(help_text='Can be multiple comma-separated answers if needed', max_length=255)),
                ('order_number', models.PositiveIntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='listening.listeningtest')),
            ],
            options={
                'db_table': 'listening_questions',
                'ordering': ['test', 'section', 'order_number'],
                'unique_together': {('test', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='ListeningAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(blank=True, max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='listening.listeningattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listening.listeningquestion')),
            ],
            options={
                'db_table': 'listening_answers',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
