# Generated by Django 4.2.30 on 2026-06-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0002_listeningtest_cambridge_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='question_group',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('matching_headings', 'Matching Headings'), ('matching_information', 'Matching Information'), ('tfng', 'True / False / Not Given'), ('ynng', 'Yes / No / Not Given'), ('summary_completion', 'Summary Completion'), ('sentence_completion', 'Sentence Completion'), ('short_answer', 'Short Answer'), ('form_completion', 'Form Completion'), ('table_completion', 'Table Completion'), ('diagram_labelling', 'Diagram Labelling'), ('drag_drop', 'Drag & Drop'), ('selection_grid', 'Selection Grid'), ('matching', 'Matching')], max_length=30),
        ),
    ]
