# Generated by Django 4.2.30 on 2026-06-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingprompt',
            name='prompt_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
