# Generated by Django 5.2.13 on 2026-04-30 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('passage_a', models.TextField(verbose_name='Passage 1')),
                ('passage_b', models.TextField(verbose_name='Passage 2')),
                ('passage_c', models.TextField(verbose_name='Passage 3')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reading_tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_score', models.PositiveIntegerField(default=0)),
                ('band_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_attempts', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.readingtest')),
            ],
            options={
                'db_table': 'reading_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage', models.CharField(choices=[('A', 'Passage 1'), ('B', 'Passage 2'), ('C', 'Passage 3')], max_length=1)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('matching_headings', 'Matching Headings'), ('matching_information', 'Matching Information'), ('tfng', 'True / False / Not Given'), ('ynng', 'Yes / No / Not Given'), ('summary_completion', 'Summary Completion'), ('sentence_completion', 'Sentence Completion'), ('short_answer', 'Short Answer')], max_length=30)),
                ('question_text', models.TextField()),
                ('correct_answer', models.CharField(help_text='Can be multiple comma-separated answers if needed', max_length=255)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('order_number', models.PositiveIntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reading.readingtest')),
            ],
            options={
                'db_table': 'reading_questions',
                'ordering': ['test', 'passage', 'order_number'],
                'unique_together': {('test', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='ReadingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(blank=True, max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reading.readingattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.readingquestion')),
            ],
            options={
                'db_table': 'reading_answers',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
