# Generated by Django 4.2.30 on 2026-06-20 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingtest',
            name='cambridge_book',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(19)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readingtest',
            name='test_number',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='readingtest',
            unique_together={('cambridge_book', 'test_number')},
        ),
        migrations.RemoveField(
            model_name='readingtest',
            name='difficulty',
        ),
    ]
