# Generated by Django 4.2.30 on 2026-06-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_readingtest_cambridge_book_readingtest_test_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingquestion',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
