# Generated by Django 4.2.30 on 2026-06-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_readingquestion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('multiple_choice_multiple', 'Multiple Choice (Multiple Answers)'), ('matching_headings', 'Matching Headings'), ('matching_information', 'Matching Information'), ('tfng', 'True / False / Not Given'), ('ynng', 'Yes / No / Not Given'), ('summary_completion', 'Summary Completion'), ('sentence_completion', 'Sentence Completion'), ('short_answer', 'Short Answer')], max_length=30),
        ),
    ]
