# Generated by Django 4.2.30 on 2026-06-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0004_readingquestion_multiple_choice_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingtest',
            name='passage_a_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='readingtest',
            name='passage_b_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='readingtest',
            name='passage_c_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
