# Generated by Django 4.2.30 on 2026-07-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0005_readingtest_passage_a_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('multiple_choice_multiple', 'Multiple Choice (Multiple Answers)'), ('matching_headings', 'Matching Headings'), ('matching_information', 'Matching Information'), ('tfng', 'True / False / Not Given'), ('ynng', 'Yes / No / Not Given'), ('summary_completion', 'Summary Completion'), ('sentence_completion', 'Sentence Completion'), ('short_answer', 'Short Answer'), ('form_completion', 'Form Completion'), ('table_completion', 'Table Completion')], max_length=30),
        ),
    ]
