# Generated by Django 5.2.13 on 2026-05-01 04:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('definition', models.TextField()),
                ('example_sentence', models.TextField()),
                ('topic', models.CharField(choices=[('environment', 'Environment'), ('technology', 'Technology'), ('health', 'Health'), ('education', 'Education'), ('society', 'Society'), ('science', 'Science'), ('business', 'Business'), ('culture', 'Culture')], max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Audio Pronunciation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vocabulary_words',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='UserWordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('known', 'Known')], default='new', max_length=20)),
                ('next_review_date', models.DateField(default=django.utils.timezone.now)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_progress', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.vocabularyword')),
            ],
            options={
                'db_table': 'user_word_progress',
                'ordering': ['next_review_date'],
                'unique_together': {('user', 'word')},
            },
        ),
    ]
